theme: jekyll-theme-tactile
layout: default
title: Travis Michels
description: Award Winning Broadcast Meteorologist
social media:
  linkedin: travis-michels-2500216b
  facebook: meteorologisttravis.michels
  twitter: weathermichels
  youtube: weathermichels
  instagram: weathermichels
image: Website/4-1.jpg
